### ISSUE TITLE
Python library files should not be included

### ISSUE THREAD

**Issue by ibra-kdbra** [susalulmumaO12/quizz_ybot#1]
# Recommended `.gitignore` Setup for Python Projects

To enhance your repository’s security and avoid tracking unnecessary files like virtual environments and binaries, you should include the following entries in your `.gitignore` file:

```sh
.Python
[Bb]in
[Ii]nclude
[Ll]ib
[Ll]ib64
[Ll]ocal
[Ss]cripts
pyvenv.cfg
.venv
pip-selfcheck.json
```

## Why This Matters:
Adding these rules to your `.gitignore` file protects sensitive information, such as environment-specific configurations or system paths, while also preventing unnecessary files from cluttering your repository. It helps keep your codebase clean and focused on actual project files.

**Comment by susalulmumaO12** [comment]
I didn't know that, thank you for the information, I thought it should be included in .gitattributes file, I will work on that.

#### Question:

If someone were to clone the project, how would they be able to get the libs and run the project?

I know that something like a package manager should be used in such case, but that means I should provide a file where a package manager can detect it right?

**Comment by ibra-kdbra** [comment]
Make a requirements.txt file that include the libraries you are using like this:

```py
<library_name>==<version_number>
annotated-types==0.5.0
anyio==3.7.1
```

You can also leave the version_number empty, if you wanted the latest library version.
Reference to a valuable [question](https://www.reddit.com/r/Python/comments/j3ilta/best_practice_for_requirementstxt_and_setuppy/).

**Comment by susalulmumaO12** [comment]
Thank you very much for the help, I'll work on that.

**Comment by ibra-kdbra** [comment]
close this issue....
