### ISSUE TITLE
Simple but important

### ISSUE THREAD

**Issue by ibra-kdbra** [susalulmumaO12/quizz_ybot#8]
Learn to add License to every project you have, the license should depend on the use-case of the project(repository).
See [this](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

I recommend a `OSL-3.0` or `Apache-2.0` or the simple `MIT`.

**Comment by susalulmumaO12** [comment]
Thank you, I was saving it for last until the project is _done_.

But since you recommend looking into it earlier, I will.

**Comment by ibra-kdbra** [comment]
I opened this Issue when I saw the fork.

**Comment by susalulmumaO12** [comment]
It never occurred to me, thanks for telling me.

**Comment by ibra-kdbra** [comment]
Yup, yup, yup.
